### ISSUE TITLE
Update dry-struct dependency

### ISSUE THREAD

**Issue by ngoral** [ScotterC/pinecone#20]
The whole chain of dependencies is narrowed to using `dry-logic, ~> 1.3.0`, which unfortunately [crashes](https://github.com/dry-rb/dry-logic/issues/104) `irb` if autocomplete is turned on.
This is fixed in `dry-logic` of `1.5.0`, but it depends on `dry-core, >=1.0`. The current version of  `dry-struct` has `dry-core, ~> 0.9` requirement, which prevents `dry-logic` from the update.

An update to `dry-struct, ~> 0.1.6` would solve the problem. Do you see any problems with that? Both changelogs for [dry-struct](https://github.com/dry-rb/dry-struct/blob/main/CHANGELOG.md) and [dry-core](https://github.com/dry-rb/dry-core/blob/main/CHANGELOG.md) do not show any criminal.

**Comment by ScotterC** [comment]
I've been trying to figure out that crash as well! Thanks for narrowing it down! I'll get that updated asap.

**Comment by ScotterC** [comment]
gem 0.1.71 pushed. Sorry I didn't get to this issue for a few days. I'm super grateful you tracked down that crash. It was infuriating :)
