### ISSUE TITLE
Unable to upsert embeddings

### ISSUE THREAD

**Issue by fsndzomga** [ScotterC/pinecone#28]
Hello,

I am unable to upsert embeddings and I do not know why. I was able to create a pinecone index but when I try upserting, nothing happens. Can you help ?

@pinecone.create_index({
        "metric": "cosine",
        "name": index_name,
        "dimension": 1536,
      })

      index = @pinecone.index(index_name)

      begin
        index.upsert(embeddings)
      rescue => e
        # Log the error for debugging purposes
        Rails.logger.error("Error during upsert operation: #{e.message}")
        Rails.logger.error(e.backtrace.join("\n"))

        # Handle the error (you can customize this based on what you want to do)
        # For example, redirect the user to an error page or display a flash message.
      end

**Comment by ScotterC** [comment]
This usually comes down to how embeddings are structured when passed to upsert. Check out the [spec](https://github.com/ScotterC/pinecone/blob/main/spec/pinecone/vector_spec.rb#L14) for a more detailed sense of what Pinecone is expecting.

**Comment by fsndzomga** [comment]
Thank you for the feedback. Indeed, it was partly because I didn't add curly braces:

`response = index.upsert({ vectors: embeddings })`

The other reason was that, when the index has just been created, it needs a bit of time before being ready for upserting. I had to do this for it to work.

`response = index.upsert({ vectors: embeddings })

while response["code"] == 9
  puts "Encountered error. Retrying in 10 seconds..."
  sleep(10)  # Wait for 10 seconds before retrying
  response = index.upsert({ vectors: embeddings })
end`

I wonder if it would be nice to add all the retry logic directly in this library ? If you agree with that vision, I can work on it and let you check and validate the retry logic @ScotterC

**Comment by ScotterC** [comment]
I have similar code in my application. 

```ruby
backoff.until_success do |interval, retry_count|
        Rails.logger.debug "Waiting for Index to be live..."
        response = client.describe_index(name)
        response.parsed_response.dig("status", "ready")
      end

```

You can sue the describe call to know when it's ready. 

Let's say we want create_index to return an index object when it's ready. What would be your approach to building that?
