### ISSUE TITLE
Add support for serverless indexes if it is not yet the case.

### ISSUE THREAD

**Issue by fsndzomga** [ScotterC/pinecone#34]
Pinecone recently introduced serverless indexes that seem cheaper than regular pods.
I tried switching from an S1 pod to a serverless index and all my insert operations stopped working. I think the syntax to make API calls is a bit different. Here is an example from pinecone documentation:

"PINECONE_API_KEY="YOUR_API_KEY"

curl -s -X POST "https://api.pinecone.io/indexes" \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -H "Api-Key: $PINECONE_API_KEY" \
  -d '{
         "name": "serverless-index",
         "dimension": 1536,
         "metric": "cosine",
         "spec": {
            "serverless": {
               "cloud": "aws",
               "region": "us-west-2"
            }
         }
      }'

# The `GET` request below uses the unique endpoint for an index.
# See https://docs.pinecone.io/docs/get-index-endpoint for details.
INDEX_HOST="INDEX_HOST"

curl -X GET "https://$INDEX_HOST/vectors/upsert" \
  -H "Accept: application/json" \
  -H "Content-Type: application/json" \
  -H "Api-Key: $PINECONE_API_KEY" \
  -d '{
    "vectors": [
      {
        "id": "doc1#chunk1", 
        "values": [0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      },
      {
        "id": "doc1#chunk2", 
        "values": [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2]
      },
      {
        "id": "doc1#chunk3", 
        "values": [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3]
      },
      {
        "id": "doc1#chunk4", 
        "values": [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]
      }
    ],
    "namespace": "ns1"
  }'"

**Comment by fsndzomga** [comment]
I might be wrong, if so let me know.
I created my serverless index manually, then got it like this:

index = @pinecone.index("discute")

response = index.upsert(
  namespace: namespace,
  vectors: embeddings
)

**Comment by ScotterC** [comment]
Did your upsert command work when the index was an S1? What does the response return now?

**Comment by fsndzomga** [comment]
Yes I finally switched back to an S1 and it worked.

When I use a serverless index here is the error I get:

""error_message":"Failed to open TCP connection to controller.eu-west-2.pinecone.io:443 (getaddrinfo: nodename nor servname provided, or not known)","error_class":"SocketError","failed_at":1707279445.5361679,"

**Comment by fsndzomga** [comment]
Perfect thank you. I moved to Pinecone 1.0 and it worked.

**Comment by ScotterC** [comment]
👍
